basePath: /api/v1
definitions:
  main.UserCommandDto:
    properties:
      age:
        type: integer
      password:
        type: string
      username:
        type: string
    required:
    - age
    - password
    - username
    type: object
host: localhost:8000
info:
  contact: {}
  description: Minimal Gin + Swagger example
  title: Example API
  version: "1.0"
paths:
  /user/add:
    post:
      consumes:
      - multipart/form-data
      description: add user
      parameters:
      - description: enter the name
        in: formData
        name: name
        required: true
        type: string
      - description: enter the family
        in: formData
        name: family
        required: true
        type: string
      - description: image
        in: formData
        name: file_data
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: adding new user
      tags:
      - User
  /user/userdetail:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: send id
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserCommandDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
schemes:
- http
swagger: "2.0"
