basePath: /api/v1
definitions:
  main.UserCommandDto:
    properties:
      age:
        type: integer
      password:
        type: string
      username:
        type: string
    required:
    - age
    - password
    - username
    type: object
host: localhost:8000
info:
  contact: {}
  description: Minimal Gin + Swagger example
  title: Example API
  version: "1.0"
paths:
  /user/userdetail:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: send id
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserCommandDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
schemes:
- http
swagger: "2.0"
